/// Flutter icons MyFlutterAppIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterAppIcons
///      fonts:
///       - asset: fonts/MyFlutterAppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';
import 'package:flutter/material.dart';

class MyFlutterAppIcons {
  MyFlutterAppIcons._();

  static const _kFontFam = 'MyFlutterAppIcons';
  static const String? _kFontPkg = null;

  static const IconData youtube = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}